test:
    loglevel: info
    storage: local
    storage_path: /tmp/test
    secret_key: foobar42
    s3_access_key: _env:S3_ACCESS_KEY
    s3_secret_key: _env:S3_SECRET_KEY
    s3_bucket: _env:S3_BUCKET
