language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -rtests/requirements.txt
  - pip install hacking==0.8.1
  - pip install .

script: flake8 . && python setup.py nosetests

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install build-essential python-dev libevent-dev python-pip liblzma-dev

